### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by lucasliet** [lucasliet/Burguerstrap#1]
- [x] **WIDGET de rede social**
- [x] **preencher _lorem ipsum_** na legenda do carrossel
- [x] editar site de acordo com a **persona**
- [x] melhorar esse design do **sobre nós**
- [x] colocar **links das redes sociais** nos href do footer @DjowNathan 
- [x] **mockup**
- [x] documentar o resultado da **pesquisa**
- [x] criar **persona**
- [x]  wireframe**
- [x] **dropdown** pela direita no footer
- [x] melhorar contraste das arrows no card de curriculo
- [x] seletor de foto no carrossel não funciona
- [x] criar o **widget**
- [x] criar **logomarca**
- [x] corrigir links do **footer**
- [x] corrigir legenda do carrossel

**Comment by lucasliet** [comment]
### Wireframe do Kalili
![A2 - Kalili](https://user-images.githubusercontent.com/49222261/68993654-428efc80-0859-11ea-8e92-7af505d7f7a8.jpg)

**Comment by LeoGil** [comment]
Tentei dar uma olhada por cima desse contraste dos Arrow não consegui resolver, vou dar uma pesquisada mais afundo pra ver

**Comment by LeoGil** [comment]
> Tentei dar uma olhada por cima desse contraste dos Arrow não consegui resolver, vou dar uma pesquisada mais afundo pra ver

Feito

**Comment by lucasliet** [comment]
Deixei a logo basicamente um botão agora, acho que compensa tirar a "home" né? tá redundante
e tem um fadezinho de transição entre as páginas agora também, olha lá

**Comment by LeoGil** [comment]
> Deixei a logo basicamente um botão agora, acho que compensa tirar a "home" né? tá redundante
> e tem um fadezinho de transição entre as páginas agora também, olha lá

Ficou bacana o fade, o botão da Home não sei se tira, pq tem pessoas que não sabe se clicar no logo volta ta ligado

**Comment by lucasliet** [comment]
> 
> 
> > Deixei a logo basicamente um botão agora, acho que compensa tirar a "home" né? tá redundante
> > e tem um fadezinho de transição entre as páginas agora também, olha lá
> 
> Ficou bacana o fade, o botão da Home não sei se tira, pq tem pessoas que não sabe se clicar no logo volta ta ligado

então, por isso que deixei antes e nem comentei HAHAHA
mas agora a logo é um botão animado e tudo
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49222261/69262953-1ea62080-0ba3-11ea-8b86-7fed594596d4.gif)

e clicar na logo pra voltar já é padrão a um tempo, instintivo fazer isso

**Comment by LeoGil** [comment]
> > > Deixei a logo basicamente um botão agora, acho que compensa tirar a "home" né? tá redundante
> > > e tem um fadezinho de transição entre as páginas agora também, olha lá
> > 
> > 
> > Ficou bacana o fade, o botão da Home não sei se tira, pq tem pessoas que não sabe se clicar no logo volta ta ligado
> 
> então, por isso que deixei antes e nem comentei HAHAHA
> mas agora a logo é um botão animado e tudo
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49222261/69262953-1ea62080-0ba3-11ea-8b86-7fed594596d4.gif)
> 
> e clicar na logo pra voltar já é padrão a um tempo, instintivo fazer isso

Eita, como gravou um gif? sauihisuahisuahs

**Comment by lucasliet** [comment]
Com Win+G gravei um vídeo, no editor de vídeo cortei os segundos que
queria, e achei um site online que faz crop no tamanho de tela e já tinha
botão mágico de transformar em Gif Hahah

Em qua, 20 de nov de 2019 2:54 PM, Leonardo Gil <notifications@github.com>
escreveu:

**Comment by LeoGil** [comment]
> * [x]  **dropdown** pela direita no footer

fiz na esquerda que ficou melhor

**Comment by lucasliet** [comment]
> * [ ]  colocar **links das redes sociais** nos href do footer

falta só o seu @DjowNathan

**Comment by lucasliet** [comment]
E o **mockup** como faremos?

**Comment by LeoGil** [comment]
> * [ ]  **WIDGET de rede social**

So encontrei alguns, mas e necessario fazer login pois ele apenas roda em seu perfil, tem o embed do proprio instagram, mas acho que ele apenas funciona com uma publicacao

**Comment by DjowNathan** [comment]
Terminei a documentação, fiz o mockup e a terceira persona, troquei os nomes para não dar ruim.
